// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VSCode.Models;

namespace vscode.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190602143727_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("VSCode.Models.Gracz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BattleTag");

                    b.Property<string>("Imie");

                    b.Property<string>("Nazwisko");

                    b.Property<string>("Pseudonim");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Gracze");
                });

            modelBuilder.Entity("VSCode.Models.osiagniecie.Osiagniecie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Nazwa");

                    b.HasKey("Id");

                    b.ToTable("Osiagniecia");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Osiagniecie");
                });

            modelBuilder.Entity("VSCode.Models.osiagniecie.OsiagniecieGracza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AktualnyStatus");

                    b.Property<int>("GraczId");

                    b.Property<int>("OsiagniecieId");

                    b.HasKey("Id");

                    b.HasIndex("GraczId");

                    b.HasIndex("OsiagniecieId");

                    b.ToTable("OsiagnieciaGracza");
                });

            modelBuilder.Entity("VSCode.Models.sezon.Ranking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GraczId");

                    b.Property<int>("Poziom");

                    b.Property<int>("PozycjaRankingowa");

                    b.Property<int>("SezonId");

                    b.HasKey("Id");

                    b.HasIndex("GraczId");

                    b.HasIndex("SezonId");

                    b.ToTable("Rankingi");
                });

            modelBuilder.Entity("VSCode.Models.sezon.Sezon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataRozpoczecia");

                    b.Property<int>("MaxIloscPunktow");

                    b.Property<int>("MinIloscPunktow");

                    b.HasKey("Id");

                    b.ToTable("Sezony");
                });

            modelBuilder.Entity("VSCode.Models.osiagniecie.OsiagniecieZaUmiejetnosc", b =>
                {
                    b.HasBaseType("VSCode.Models.osiagniecie.Osiagniecie");

                    b.Property<int>("MaksymalnyWynik");

                    b.Property<string>("Opis");

                    b.ToTable("OsiagniecieZaUmiejetnosc");

                    b.HasDiscriminator().HasValue("OsiagniecieZaUmiejetnosc");
                });

            modelBuilder.Entity("VSCode.Models.osiagniecie.OsiagniecieGracza", b =>
                {
                    b.HasOne("VSCode.Models.Gracz", "Gracz")
                        .WithMany()
                        .HasForeignKey("GraczId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VSCode.Models.osiagniecie.Osiagniecie", "Osiagniecie")
                        .WithMany()
                        .HasForeignKey("OsiagniecieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VSCode.Models.sezon.Ranking", b =>
                {
                    b.HasOne("VSCode.Models.Gracz", "Gracz")
                        .WithMany()
                        .HasForeignKey("GraczId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VSCode.Models.sezon.Sezon", "Sezon")
                        .WithMany()
                        .HasForeignKey("SezonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
